version: "3.7"
services:
  cli:
    build: ./cli
    env_file:
      - ./cli/config/secret.env
    environment:
      DB_FILE: .db
    volumes:
      - db:/cli/.db

#  admin:
#    build: ./admin
#    volumes:
#      - db:/admin/.db

volumes:
  db:
