version: "3.7"
services:
  cli:
    container_name: cli
    build: ./cli
    environment:
      DB_FILE: .db
    volumes:
      - db:/cli/.db

#  admin:
#    container_name: admin
#    build: ./admin
#    volumes:
#      - db:/admin/.db

volumes:
  db:
